language: cpp
git:
  depth: 1
matrix:
  include:
    - name: Windows Release
      os: windows
      env:
        - MSBUILD_PATH="c:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
      script:
        - export PATH=$MSBUILD_PATH:$PATH
        - cd ..
        - pwd
        - git clone https://github.com/bluewhalerobot/GalileoSDK --depth=1
        - travis_wait choco install python2 -y
        - cd pygalileo
        # travis build failed but can build successful locally
        - travis_wait MSBuild.exe pyGalileo.sln //p:configuration=release //p:platform=x64
      before_deploy:
        - mkdir -p deploy/pygalileo/
        - cp x64/Release/pygalileo.pyd deploy/pygalileo/pygalileo.pyd
        - cd deploy
        - tar -czf pygalileo-win-${TRAVIS_TAG}.tar.gz pygalileo
        - cd ..
        - mv deploy/pygalileo-win-${TRAVIS_TAG}.tar.gz ./

      deploy:
        provider: releases
        api_key: "$token"
        file: "pygalileo-win-${TRAVIS_TAG}.tar.gz"
        skip_cleanup: true
        on:
          branch: master
          tags: true
    # - name: Ubuntu 18.04 Build Test
    #   sudo: required
    #   dist: bionic
    #   before_install:
    #     - export DEBIAN_FRONTEND="noninteractive"
    #     - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
    #     - sudo apt-get update -y
    #     - sudo apt-get install -y aria2 wget
    #     - sudo wget https://raw.githubusercontent.com/ilikenwf/apt-fast/master/apt-fast -O /usr/local/sbin/apt-fast
    #     - sudo chmod +x /usr/local/sbin/apt-fast
    #     - sudo wget https://raw.githubusercontent.com/ilikenwf/apt-fast/master/apt-fast.conf -O /etc/apt-fast.conf
    #     - sudo apt-fast update -qq
    #     - sudo apt-get install -y --allow-unauthenticated libjsoncpp-dev ros-melodic-roscpp libboost-all-dev ros-melodic-geometry-msgs
    #   script:
    #     - source /opt/ros/melodic/setup.bash
    #     - export LIBRARY_PATH=/opt/ros/melodic/lib/
    #     # build and install GalileoSDK
    #     - cd ..
    #     - git clone https://github.com/bluewhalerobot/GalileoSDK --depth=1
    #     - cd GalileoSDK/GalileoSDK
    #     - mkdir build
    #     - cd build
    #     - cmake ..
    #     - make -j
    #     - sudo make install
    #     - cd ../../GalileoSDKTest
    #     - mkdir build
    #     - cd build
    #     - cmake ..
    #     - make -j
    #     - cd ../../../pygalileo/pyGalileo
    #     - mkdir build
    #     - cd build
    #     - cmake ..
    #     - make
    - name: Ubuntu 16.04 Build Test
      sudo: required
      dist: xenial
      addons:
        apt:
          update: true
          sources:
            - sourceline: 'ppa:mhier/libboost-latest'
          packages:
            - boost1.68-dev
      before_install:
        - export DEBIAN_FRONTEND="noninteractive"
        - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
        - sudo apt-get update -y
      script:
        - cd ..
        # install ros packages
        - mkdir -p amd64/src
        - cd amd64/src
        - git clone https://github.com/ros/catkin --depth=1
        - git clone https://github.com/ros/common_msgs --depth=1
        - git clone https://github.com/ros/gencpp --depth=1
        - git clone https://github.com/jsk-ros-pkg/geneus --depth=1
        - git clone https://github.com/ros/genlisp --depth=1
        - git clone https://github.com/ros/genmsg --depth=1
        - git clone https://github.com/RethinkRobotics-opensource/gennodejs --depth=1
        - git clone https://github.com/ros/genpy --depth=1
        - git clone https://github.com/ros/message_generation --depth=1
        - git clone https://github.com/ros/message_runtime --depth=1
        - git clone https://github.com/BluewhaleRobot/ros_comm --depth=1
        - git clone https://github.com/ros/ros_comm_msgs --depth=1
        - git clone https://github.com/BluewhaleRobot/rosconsole --depth=1
        - git clone https://github.com/BluewhaleRobot/roscpp_core --depth=1
        - git clone https://github.com/ros/std_msgs --depth=1
        - travis_wait 20 sudo apt-get install -yqq --allow-unauthenticated python-empy python-catkin-pkg python-catkin-tools > /dev/null
        - cd ..
        - ./src/catkin/bin/catkin_make -DCATKIN_WHITELIST_PACKAGES="" -DBUILD_SHARED_LIBS=OFF -DCATKIN_ENABLE_TESTING=OFF | awk "(NR%50)==0{print;}"
        - source ./devel/setup.bash
        - cd ../pygalileo
        # build and install GalileoSDK
        - cd ..
        - git clone https://github.com/bluewhalerobot/GalileoSDK --depth=1
        - cd GalileoSDK/IotWrapper
        - mkdir build
        - cd build
        - cmake ..
        - make
        - cd ../../iot
        - mkdir build
        - cd build
        - cmake ..
        - make
        - cd ../../GalileoSDK
        - mkdir build
        - cd build
        - cmake ..
        - make -j
        - sudo make install
        - cd ../../GalileoSDKTest
        - mkdir build
        - cd build
        - cmake ..
        - make -j
        # 缺少boost-python
        # - cd ../../../pygalileo/pyGalileo
        # - mkdir build
        # - cd build
        # - cmake ..
        # - make